name: discord message
on: [push, pull_request,]
jobs:

  build:
    name: discord notify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: The ${{ github.event_name }} event triggered first step.
