on: [push, pull_request]
name: Bot
jobs:
  build:
    name: Discord notify
    runs-on: ubuntu-latest
    steps:
        - uses: Ilshidur/action-discord@master
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
